version: '3.8'
services:
  db:
    image: postgres:14.7-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data
    env_file:
      - .env
  tg_bot:
    build: .
    image: baradabacka/dushno_and_tochka_bot:latest
    restart: always
    volumes:
      - log_volumes:/var/log/
    depends_on:
      - db
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    env_file:
      - .env
volumes:
  log_volumes:
  database_data: